### ISSUE TITLE
Perf question

### ISSUE THREAD

**Issue by v1gnesh** [simd-lite/simd-json-derive#55]
https://docs.rs/simd-json-derive/0.10.1/src/simd_json_derive/lib.rs.html#18-28

The `json_string` method calls the `json_vec` method, and the latter creates `Vec::with_capacity(512)`.
Then `json_write` is called on `self` to fill it up.

Is it possible to provide a variant where I can supply the capacity to use?
In the case where `json_string` is called in a loop on structs, allocating the vec based on the size of the each struct would be beneficial, no?

**Comment by Licenser** [comment]
There is json_write, that exists for that purpose :) https://docs.rs/simd-json-derive/latest/simd_json_derive/trait.Serialize.html#tymethod.json_write. This should be better documented so it is more obvious. `&mut Vec<u8>` implements `Write` so you can re-use your buffer :)

**Comment by v1gnesh** [comment]
With your help, I'm already using json_write for custom Serialize impls.
What I wanted to ask with the above is for the higher-level json_string, as it recursively calls json_vec -> json_write to serialize all fields within some top-level struct.
`json_string -> repeat (json_vec -> json_write) for each field`.

So, something to advise the max Vec len to use in this invocation:
```rust
Serialize::json_string(<a-big-struct>).expect("something")
```

**Comment by Licenser** [comment]
Do you have a code example? I'm not quite sure I follow and. In the json_write method it shouldn't recursively call back to write string but I have the feeling we are talking about different things

**Comment by Licenser** [comment]
I think this can be lclosed
