### ISSUE TITLE
Crash when deserializing unknown field in struct

### ISSUE THREAD

**Issue by george-lim** [simd-lite/simd-json-derive#59]
Hey there! Not sure if working with unknown fields is unsupported in `simd-json-derive`, but often I'm working with public external REST APIs that return a lot of JSON data. I only want to deserialize some fields that I'm going to work with and ignore unknown ones.

I've noticed that if the data includes an unknown field before the fields I've defined, there is a crash.

```rust
use simd_json_derive::Deserialize;
use std::error::Error;

#[derive(Debug, Deserialize)]
struct Model<'de> {
    text: &'de str,
}

fn main() -> Result<(), Box<dyn Error>> {
    // Unknown field after, no problem
    let mut json = br#"{"text":"test","unknown":123}"#.to_vec();
    println!("{:#?}", Model::from_slice(&mut json)?);

    // Unknown field before, crashes with "internal error: entered unreachable code"
    json = br#"{"unknown":123,"text":"test"}"#.to_vec();
    println!("{:#?}", Model::from_slice(&mut json)?);

    Ok(())
}
```

What is the suggested way to handle this case? I thought about listing out all the possible fields ahead of my field, and maybe using something like Serde's `IgnoreAny`, but this isn't robust since the external API could add other fields in the future.

**Comment by Licenser** [comment]
Ja that's a bug, by default unknown fields should be ignored, will fix :)
