### ISSUE TITLE
add skip_serializing_if support

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-json-derive#6]
add `#[serde(skip_serializing_if = "Option::is_none")]` support

**Comment by george-lim** [comment]
Hey @Licenser is there a workaround to this for now? I have a couple structs that have bunch of optional fields that I would love to skip serializing. Right now I've been duplicating structs without a field but this doesn't scale well.

**Comment by Licenser** [comment]
Sadly there is no workaround, it'd need to be implemented. it'd need to be properly implemented. It shouldn't be extensively hard but some work that requires time.

**Comment by george-lim** [comment]
Gotcha. Is this something you have plans to implement in the near future. If not that's totally cool, I can work with duplicate structs for now :)

**Comment by Licenser** [comment]
I took a short look at it this weekend it's not quite straightforward to implement without losing the optimisations done for writing.

The biggest thing is that before writing simd-json-derive [precomputes the name of to escape and add control characters ](https://github.com/simd-lite/simd-json-derive/blob/9d0ea0ea245c8b74efa079590106206e36e373ef/simd-json-derive-int/src/serialize.rs#L76-L81) this works if we know all fields are present, it gets more complicated if we don't we basically need to move some of the logic to runtime at this point and avoid moving all of it there if not needed. The same logic is applied in other places too.

I'd like to add it but I'm not sure when I get the time, I'll open a draft PR non the less with including the attribute and some placeholder start in case someone wants to pick it up in the meantime and drive it home.

**Comment by george-lim** [comment]
Understood, thank you so much @Licenser :)

**Comment by Licenser** [comment]
Heya,

I implemented the needed code in #64 since there might be a bunch of corner cases and I don't have an active use-case could you give the branch a try and see if it works for you? If yes I'll merge and release this

**Comment by george-lim** [comment]
Hey! Yep I can do that now, I'll test it against a couple APIs that I'm working with

**Comment by george-lim** [comment]
Yep, not only does it totally work in my case, but you just helped me shave ~10 KB off my WASM binary from deduplicating models. That's fantastic!

Thanks so much for this @Licenser, you're the best ✋

**Comment by Licenser** [comment]
sweet :D I'm glad to hear that, the code isn't super optimized but I guess it's good enough :tm: for now

**Comment by Licenser** [comment]
released as `0.11.3`

**Comment by george-lim** [comment]
sweet!
