### ISSUE TITLE
Clippy bad_bit_mask error on Deserialize

### ISSUE THREAD

**Issue by george-lim** [simd-lite/simd-json-derive#60]
Hi! Clippy seems to give a bad_bit_mask error when implementing Deserialize on a struct which has an optional field of another struct. The error originates in the Deserialize macro, but when actually deserializing there doesn't seem to be an issue. Just wondering if this is something we can safely ignore :)

```rust
#[derive(Deserialize)]
struct Child {
    foo: i32,
}

// Clippy is fine with this
#[derive(Deserialize)]
struct Parent {
    child: Child,
}

// Clippy mentions having a bad bit mask for this
#[derive(Deserialize)]
struct Parent2 {
    child: Option<Child>,
}
```

**Comment by Licenser** [comment]
if you read [what the lint is about](https://rust-lang.github.io/rust-clippy/master/index.html#/bad_bit_mask) you can see that it is about bitmasks that are always true or false and can be misleading to read. In generated code it is quite normal to not optimize for readability :)

**Comment by george-lim** [comment]
Alright, I take it it's safe to ignore then :)
