### ISSUE TITLE
Support untagged enum representation

### ISSUE THREAD

**Issue by george-lim** [simd-lite/simd-json-derive#66]
Hey @Licenser! This one is a nice to have, I'm wondering if this is something that could be easily supported.

I'm working with some external APIs that return mutually exclusive responses for successes and failures

```json
{
    "field_1": "value 1",
    "field_2": "value 2",
    "field_n": "value n"
}
```

or

```json
{
    "error": "some error description"
}
```

I can technically accomplish this with `simd-json-derive` by doing something like the following:

```rust
#[derive(Deserialize)]
pub struct ApiResponse<'de> {
    pub field_1: Option<&'de str>,
    pub field_2: Option<&'de str>,
    // ...
    pub field_n: Option<&'de str>,
    pub error: Option<&'de str>,
}
```

This is fine, but doesn't scale as well. I thought about parsing the success response first, and then falling back to parse the error response if the former fails, but the deserialize methods mutate the original data to build the tape, forcing me to clone the HTTP response body beforehand.

Looking at `serde`, it seems they solve this by allowing [untagged enum representations](https://serde.rs/enum-representations.html) to depict mutually exclusive data.

Does this look like something that makes sense to add into `simd-json-derive`? I'm fine with sticking to my current approach (unless I missed a better solution). As always, really appreciate the work that has gone into this :)

**Comment by Licenser** [comment]
Puh this is a tough one, especially tough doing performant as the macro will need to figure out how to distinguish them. It seems even serde [takes shortcuts here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5baa1cec39e9d041d78f60bf88ed654c) and doesn't validate that the enum can be safely used untagged (no criticism on serde here it does a much better job with derives them simd-json derive ;) ) but getting it right is tricky.


I suspect the "easy" way is to deserialize all keys from all variants into options and then go through the variants and which keys they require in order but even that is quite a bit of work to implement.


A quick option (in your case) if this is a common pattern in the interface is implementing a function like (this is pseudo code):

```rust

struct Error<'a> {
error: &'a str
}
struct Response<'a> {
// ...
  field_n: &'a str
// ...
parse_with_error_response<T: Deserialize>(data: &mut [u8]) -> Result<T, Error>{
let tape = simd_json::to_tape(data)?;
if [Node::Object{len: 1, count: 2}), Node::String("error")] = tape.get(..2) {
  Err(Error::from_tape(tape)?))
} else {
  Ok(T::from_tape(tape)?)
}
}
```

**Comment by george-lim** [comment]
Hmm I couldn't get your code to work. Could you also help me understand how that if statement works? like what each element in the slice represents? It seems like we are ignoring the first element, and also the second element seemingly represents the outer object, but I don't get why it has length 1 and count 2.

```rust
use simd_json::Node;
use simd_json_derive::Deserialize;

#[derive(Debug, Deserialize)]
pub struct LoginResponse<'de> {
    pub foo: &'de str,
}

#[derive(Debug, Deserialize)]
pub struct ErrorResponse<'de> {
    pub error: &'de str,
}

#[derive(Debug)]
enum Response<'de> {
    LoginResponse(LoginResponse<'de>),
    Error(ErrorResponse<'de>),
}

fn parse(data: &mut [u8]) -> Result<Response, Box<dyn std::error::Error>> {
    let tape = simd_json::to_tape(data)?;

    match tape.get(..2) {
        Some([_, Node::Object { len: 1, count: 2 }, Node::String("error")]) => {
            let mut itr = tape.into_iter().peekable();
            itr.next();
            Ok(Response::Error(ErrorResponse::from_tape(&mut itr)?))
        }
        Some(_) => {
            let mut itr = tape.into_iter().peekable();
            itr.next();
            Ok(Response::LoginResponse(LoginResponse::from_tape(&mut itr)?))
        }
        None => panic!(""),
    }
}

fn main() {
    let mut data = br#"{"error":"hello world!"}"#.to_vec();
    println!("{:#?}", parse(&mut data))
}
```

**Comment by Licenser** [comment]
Sorry for the late reply. I was deep into simd-json with some significant changes and needed some focus :).

So the first element of a tape is always a `null` value that can be safely ignored. That's an implementation detail of simdjson.

The object has two properties, len and count. They represent the logical and factual properties of the object:

- Len: the number of key-value pairs in the object
- count: the number of tape nodes that are in the object

In this case we know that the error response has exactly one key-value pair, ("error") so the `len` is `1`. We also know that both the key and the value are strings and not include any nested structures (arrays and objects), so they willl be represented by two nodes in the tape - `count` is `2` in this case. 


I've taken your code and re-wrote it slightly from my original code, this is now fully working :)



```rust
use simd_json::Node;
use simd_json_derive::Deserialize;

#[derive(Debug, Deserialize)]
pub struct LoginResponse<'de> {
    pub foo: &'de str,
}

#[derive(Debug, Deserialize)]
pub struct ErrorResponse<'de> {
    pub error: &'de str,
}

#[derive(Debug)]
enum Response<'de> {
    LoginResponse(LoginResponse<'de>),
    Error(ErrorResponse<'de>),
}

fn parse(data: &mut [u8]) -> Result<Response, Box<dyn std::error::Error>> {
    let tape = simd_json::to_tape(data)?;

    if let [_, Node::Object { len: 1, count: 2 }, Node::String("error"), Node::String(error)] =
        tape.as_slice()
    {
        Ok(Response::Error(ErrorResponse { error }))
    } else {
        let mut itr = tape.into_iter().peekable();
        itr.next();
        Ok(Response::LoginResponse(LoginResponse::from_tape(&mut itr)?))
    }
}

fn main() {
    let mut data = br#"{"error":"hello world!"}"#.to_vec();
    println!("{:#?}", parse(&mut data))
}
```

**Comment by george-lim** [comment]
Got it! Thanks for the explanation regarding `len` and `count` as well. I have verified that this works, I'll be using this going forward. I'll close this issue now :)
