### ISSUE TITLE
Error when deserializing into &str slice in release mode

### ISSUE THREAD

**Issue by george-lim** [simd-lite/simd-json-derive#67]
Hey! I created a MRE for a bug I encountered below. This code compiles and works in debug mode, but in release the `FooStr` struct will not successfully deserialize.

```rust
use simd_json_derive::Deserialize;

#[derive(Deserialize)]
struct FooString {
    foo: String,
}

#[derive(Deserialize)]
struct FooStr<'de> {
    foo: &'de str,
}

fn main() {
    // This works fine in both debug and release mode (opt-level = 3)
    let mut json = br#"{"foo":"bar"}"#.to_vec();
    println!("{}", FooString::from_slice(&mut json).unwrap().foo);

    // This works fine in debug but fails in release mode (opt-level = 3)
    let mut json = br#"{"foo":"bar"}"#.to_vec();
    println!("{}", FooStr::from_slice(&mut json).unwrap().foo);
}
```

**Comment by Licenser** [comment]
Hi,

good catch! I added a test:


```rust
#[test]
fn foo_str() {
    #[derive(Deserialize)]
    struct FooStr<'de> {
        foo: &'de str,
    }
    let mut json = br#"{"foo":"bar"}"#.to_vec();
    let res = FooStr::from_slice(&mut json);
    assert!(res.is_ok());
    assert_eq!(res.unwrap().foo, "bar");
}
```

Clearly a bug, not a panic however, it returns a Err the panic comes from the `unwrap()` I'll rename the issue and see how quick I can fix it :)

**Comment by george-lim** [comment]
oh yeah whoops I wasn't paying attention when I wrote the MRE, just threw unwrap for convenience haha

**Comment by Licenser** [comment]
This is a really tricky  one, I can reproduce it but I can't make sense of it so far

**Comment by george-lim** [comment]
Not sure if this helps, but I found out that the following works (just like String) on release

```
#[derive(Deserialize)]
struct FooOptionStr<'de> {
    foo: Option<&'de str>,
}
```

Which leads me to believe that it's not necessarily the string slice part itself that's getting optimized out. When you wrap it in an enum it's fine.

**Comment by Licenser** [comment]
Okay, this took a lot of digging, but I found it. The use of `MaybeUninit` and `.assume_init()` was wrong and led to undefined behavior. This didn't pop up in the release code but optimisations lead to (I assume) freeing of memory that shouldn't have been freed.

The rewrite of the deserializer avoids `MaybeUninit` altogether in favour of Option's at the cost of some performance, but the code is free of unsafe and sound.

I'll release this as 0.12.0 along with an entry in the `advisory-db` to push people to update form 0.11 (or earlier)
