### ISSUE TITLE
Restson Rust crate compatibility

### ISSUE THREAD

**Issue by suuvor** [simd-lite/simd-json-derive#7]
Hello!

[Restson Rust](https://github.com/spietika/restson-rust) crate uses serde library to deserialize data from REST-service. In what way can simd-json-derive be used to deserialize the data by simd_json_derive?

When I am trying to use simd_json_derive with Restson crate,

```
use simd_json_derive::{Deserialize, Serialize};
#[derive(Deserialize, Debug)]
struct Event {
    id: u64
}
let mut client = RestClient::new("https://some-api.com").unwrap();
let data : Event = client.get(()).unwrap();
```
 I have the next error in get() method:
`^^^ the trait `for<'de> serde::de::Deserialize<'de>` is not implemented for `Event``

Restson deserializing code is:
`serde_json::from_str(body.as_str()).map_err(|err| Error::DeserializeParseError(err, body))`

Can this problem be resolved in any way?
Probably Ruston crate should use simd_json option to deserialize data, shouldn't it?
Thanks

**Comment by Licenser** [comment]
Sorry for the late reply, I'm terrible at managing github notifications :/

the serde::Deserialize trait isn't implemented  with simd_json_derive, it uses a very different and custom model that focuses on performance.

you could change the RustClient to return that trait, alternatively you could get the data as bytes and call `Event::from_slice` or `Event::from_vec`

**Comment by Licenser** [comment]
I think this can be closed by now, feel free to re-open if requried
